### ISSUE TITLE
Stops minifying if there's a style element in the template literal?

### ISSUE THREAD

**Issue by morewry** [asyncLiz/rollup-plugin-minify-html-literals#1]
Is this intentional?

I am trying this out and find it only works if my tagged template literals don't have a `<style>` element inside them. If I add `<style>`, I end up with `\n` and spaces in my bundle. If I remove it, `\n` and spaces go away. Add it back, they come back. It repeats reliably.

But the documentation of https://github.com/asyncLiz/minify-html-literals shows an example that minifies and includes `<style>`...?

PS: This is different from the CSS _inside_ the `<style>` being minified or not. I mean the whole template literal, not the CSS. (My CSS _is_ minified, but by PostCSS+cssnano, so that's tangential.)

**Comment by morewry** [comment]
In fact, it stops minifying if I have a template literal with a `<style>` tag _anywhere in the file_. I tried working around it by breaking them into two different template strings and joining those together.

**Comment by asyncLiz** [comment]
Hey @morewry! Thanks for the issue. Can you let me know what version of this module you are using? I'm unable to replicate on the latest version 1.0.7. Template literals with `<style>` are minified correctly for me.

**Comment by asyncLiz** [comment]
When I run minifyHTMLLiterals on that string with the default options, I get this as the result:
```
import * as page from \'./page.css\';\nimport { default as html } from \'tagged-template-noop\';\n\nfunction _getFullTemplate() {\n  const template = html`<style>.stuff{background:#00f}</style><section id=page class=${page.page}><div class="${\n        page.pageWarn\n }" role=complementary aria-label="Service Warning"><slot name=page-warn></slot></div><header class=${page.pageHead} role=banner><svg class=${page.pageHeadLogo}></svg><nav class=${page.pageHeadMenu} aria-label=TODO><slot name=page-head-menu></slot></nav></header><nav class=${page.pageMenu} aria-label=TODO><slot name=page-menu></slot></nav><main class=${page.pageMain}><slot name=page-main><slot></slot></slot></main><footer class=${page.pageFoot} role=contentinfo><slot name=page-foot></slot></footer></section>`;\n  // TODO: workaround for https://github.com/asyncLiz/rollup-plugin-minify-html-literals/issues/1\n  return [template, \'<style>\', page.styles, \'</style>\'].join(\'\');\n}\n
```

It definitely looks like it's minifying, even with style tags. Now, it _won't_ minify the JS newlines and spaces in the placeholder sections. For example, you have 
```
<div class="${
  page.pageWarn
}" 
```
The html around the `${ }` placeholder will be minified, but not the JS inside, which contains newlines and spaces. After minifying the html literals, a pass through uglify or any other JS minifier will remove those.

Could that be what you're seeing? I don't see any JS minify step in your rollup config such as `rollup-plugin-terser`.

**Comment by morewry** [comment]
No, I don't think so. 

WIth my workaround above, this is my output:

```javascript
['<section id=page class="', ' ', '"><div class="', '" role=complementary aria-label="Service Warning"><slot name=page-warn></slot></div><header class=', ' role=banner><svg class=', '></svg><nav class=', ' aria-label=TODO><slot name=page-head-menu></slot></nav></header><nav class=', ' aria-label=TODO><slot name=page-menu></slot></nav><main class=', '><slot name=page-main><slot></slot></slot></main><footer class=', ' role=contentinfo><slot name=page-foot></slot></footer></section>']
```

If I do this instead, this is my output:

```javascript
html`
  <section id="page"
      class="${page.page} ${classNames}">
    <div class="${
      page.pageWarn
    }" role="complementary" aria-label="Service Warning">
      <slot name="page-warn"></slot>
    </div>
    <header class="${page.pageHead}" role="banner">
      <svg class="${page.pageHeadLogo}"></svg>
      <nav class="${page.pageHeadMenu}" aria-label="TODO">
        <slot name="page-head-menu"></slot>
      </nav>
    </header>
    <nav class="${page.pageMenu}" aria-label="TODO">
      <slot name="page-menu"></slot>
    </nav>
    <main class="${page.pageMain}">
      <slot name="page-main">
        <slot></slot>
      </slot>
    </main>
    <footer class="${page.pageFoot}" role="contentinfo">
      <slot name="page-foot"></slot>
    </footer>
  </section>
  <style>${page.styles}</style>
`;
```

```
['\n    <section id="page"\n        class="', ' ', '">\n      <div class="', '" role="complementary" aria-label="Service Warning">\n        <slot name="page-warn"></slot>\n      </div>\n      <header class="', '" role="banner">\n        <svg class="', '"></svg>\n        <nav class="', '" aria-label="TODO">\n          <slot name="page-head-menu"></slot>\n        </nav>\n      </header>\n      <nav class="', '" aria-label="TODO">\n        <slot name="page-menu"></slot>\n      </nav>\n      <main class="', '">\n        <slot name="page-main">\n          <slot></slot>\n        </slot>\n      </main>\n      <footer class="', '" role="contentinfo">\n        <slot name="page-foot"></slot>\n      </footer>\n    </section>\n    <style>', '</style>\n  ']
```

It really looks to me like the HTML minification completely stops working.

**Comment by asyncLiz** [comment]
I'll put together a full repro tonight to help you figure it out

**Comment by morewry** [comment]
That's very, very kind of you!

**Comment by asyncLiz** [comment]
I figured out the problem! I'm using a string to replace the template literal placeholders when I minify so that the final minified html can be split back into the correct literal parts. The problem is that
```
<style>${page.styles}</style>
```
gets turned into
```
<style>TEMPLATE_EXPRESSION</style>
```
and then is minified to
```
<style></style>
```
When minify-html-literals tries to break the minified string apart, it sees that there's a mismatch with the number of expected parts and throws an exception `(!) minify-html-literals plugin: splitHTMLByPlaceholder() must return same number of strings as template parts`.

The culprit is css-clean who correctly removes the nonsense characters from the style tag. I was able to fix it by changing the placeholder string to `@TEMPLATE_EXPRESSION();`.

@morewry can you try updating to 1.1.1 and see if that fixes your problem?

**Comment by morewry** [comment]
Awesome! Yes, I'll do it this evening and let you know.

**Comment by morewry** [comment]
@asyncLiz Sorry for the delay on verifying. I installed `^1.1.1` and removed my workaround and have no further issues.

Very much appreciate your help and quick fix!
