### ISSUE TITLE
Variable within an HTML comment throws exception

### ISSUE THREAD

**Issue by flyweight** [asyncLiz/rollup-plugin-minify-html-literals#11]
Using the default settings, a variable inside of an HTML comment throws the following error:

`UnhandledPromiseRejectionWarning: Error: splitHTMLByPlaceholder() must return same number of strings as template parts`

This can be fixed by escaping the $
```javascript
const { minifyHTMLLiterals } = require('minify-html-literals');
const contents = `
class {
  render() {
  const myVar = '';
  return html\`
    <html>
    <!-- comment \${myVar} -->
    </html>
  \`;
  }
}
`;

console.log(minifyHTMLLiterals(contents));
```

**Comment by asyncLiz** [comment]
The problem is that the default minify options remove HTML comments. The comment is being removed, and the library doesn't know where to put `${myVar}` back. 

You can fix this by setting `removeComments: false` in the minify options.

```js
const { minifyHTMLLiterals, defaultMinifyOptions } = require('minify-html-literals');
const contents = `
class {
  render() {
  const myVar = '';
  return html\`
    <html>
    <!-- comment \${myVar} -->
    </html>
  \`;
  }
}
`;

console.log(minifyHTMLLiterals(contents, {
  minifyOptions: {
    ...defaultMinifyOptions,
    removeComments: false
  }
}));
```
